const test=require('node:test'),assert=require('node:assert/strict'),Q=require('../erhu-quality');
test('missing quiz and real zero remain distinct',()=>{assert.equal(Q.quiz(null).lastScore,null);assert.equal(Q.quiz({lastScore:0,bestScore:0,total:10}).available,true);assert.match(Q.report({quiz:Q.quiz(null)}),/尚無成績/);assert.match(Q.report({quiz:Q.quiz({lastScore:0,bestScore:0,total:10})}),/最近 0 \/ 10/);});
test('plan allocations always sum exactly to requested budget',()=>{for(const minutes of [15,25,45,60])for(let n=1;n<=8;n++){const tasks=Array.from({length:n},(_,i)=>({title:'task'+i,minutes:(i+1)*7}));const plan=Q.schedule(minutes,tasks);assert.equal(plan.reduce((s,x)=>s+x.minutes,0),minutes);assert.ok(plan.every(x=>Number.isInteger(x.minutes)&&x.minutes>0));}});
test('grade navigation crosses segment boundaries',()=>{assert.deepEqual(Q.gradeNeighbor('beginner',3,1),{level:'intermediate',grade:1});assert.deepEqual(Q.gradeNeighbor('advanced',1,-1),{level:'intermediate',grade:4});assert.equal(Q.gradeNeighbor('advanced',3,1),null);assert.equal(Q.gradeNeighbor('beginner',1,-1),null);});
test('shuffle preserves answer identity',()=>{for(const rng of [()=>0,()=>.4,()=>.99]){const q=Q.shuffled({options:['correct','wrong','also wrong'],answer:0},rng);assert.equal(q.options[q.answer],'correct');}});
test('score validation flags uncertain notes and rhythm without inventing notes',()=>{const score={beatUnits:4,header:{left:['1=D','4/4']},rows:[{measures:[{cells:[{label:"1'.",units:3},{label:'?',units:1,uncertain:true}],underlines:[[0,1,1]]}]}]};const before=JSON.stringify(score),result=Q.validateScore(score);assert.equal(result.cells,2);assert.ok(result.warnings.length>=2);assert.equal(JSON.stringify(score),before);});
test('invalid score span is rejected instead of drawing misleading notation',()=>{assert.throws(()=>Q.validateScore({rows:[{measures:[{cells:[{label:'1',units:4}],slurs:[[0,3]]}]}]}));});
test('markdown escapes executable HTML',()=>{const html=Q.markdown('**重點**\n<img src=x onerror=alert(1)>');assert.match(html,/<strong>重點<\/strong>/);assert.ok(!html.includes('<img'));});
test('microphone failure has actionable Chinese recovery',()=>{assert.match(Q.micError({name:'NotFoundError'}),/找不到麥克風/);assert.match(Q.micError({name:'NotAllowedError'}),/權限/);});
